services:
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:
      - "54327:5432"
    environment:
      - POSTGRES_PASSWORD=wt010605
      - POSTGRES_USER=wattanapat
      - POSTGRES_DB=wattanapat
    volumes:
      - .data/data:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4:latest
    container_name: 69-s1-admin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=kittikoon-p@rmutp.ac.th
      - PGADMIN_DEFAULT_PASSWORD=wt010605
